extern NSString* const METHOD_NAME_CREATE_CLIENT;
extern NSString* const METHOD_NAME_DESTROY_CLIENT;

extern NSString* const METHOD_NAME_ENABLE;
extern NSString* const METHOD_NAME_DISABLE;

extern NSString* const METHOD_NAME_START_SCAN;
extern NSString* const METHOD_NAME_STOP_SCAN;

extern NSString* const METHOD_NAME_CONNECT;
extern NSString* const METHOD_NAME_CANCEL_CONNECTION_OR_DISCONNECT;
extern NSString* const METHOD_NAME_IS_DEVICE_CONNECTED;

extern NSString* const METHOD_NAME_READ_RSSI;
extern NSString* const METHOD_NAME_REQUEST_CONNECTION_PRIORITY;
extern NSString* const METHOD_NAME_REQUEST_MTU;

extern NSString* const METHOD_NAME_GET_KNOWN_DEVICES;
extern NSString* const METHOD_NAME_GET_CONNECTED_DEVICED;

extern NSString* const METHOD_NAME_DISCOVERY;

extern NSString* const METHOD_NAME_READ_CHARACTERISTIC;
extern NSString* const METHOD_NAME_READ_CHARACTERISTIC_FOR_SERVICE;
extern NSString* const METHOD_NAME_READ_CHARACTERISTIC_FOR_DEVICE;

extern NSString* const METHOD_NAME_WRITE_CHARACTERISTIC;
extern NSString* const METHOD_NAME_WRITE_CHARACTERISTIC_FOR_SERVICE;
extern NSString* const METHOD_NAME_WRITE_CHARACTERISTIC_FOR_DEVICE;

extern NSString* const METHOD_NAME_MONITOR_CHARACTERISTIC;
extern NSString* const METHOD_NAME_MONITOR_CHARACTERISTIC_FOR_SERVICE;
extern NSString* const METHOD_NAME_MONITOR_CHARACTERISTIC_FOR_DEVICE;

extern NSString* const METHOD_NAME_READ_DESCRIPTOR;
extern NSString* const METHOD_NAME_READ_DESCRIPTOR_FOR_CHARACTERISTIC;
extern NSString* const METHOD_NAME_READ_DESCRIPTOR_FOR_SERVICE;
extern NSString* const METHOD_NAME_READ_DESCRIPTOR_FOR_DEVICE;

extern NSString* const METHOD_NAME_WRITE_DESCRIPTOR;
extern NSString* const METHOD_NAME_WRITE_DESCRIPTOR_FOR_CHARACTERISTIC;
extern NSString* const METHOD_NAME_WRITE_DESCRIPTOR_FOR_SERVICE;
extern NSString* const METHOD_NAME_WRITE_DESCRIPTOR_FOR_DEVICE;

extern NSString* const METHOD_NAME_CANCEL_TRANSACTION;
